default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: league_development
  username: jgrishey
  password: 

test:
  <<: *default
  database: league_test
  username: jgrishey
  password: 

production:
  <<: *default
  database: league_production
  username: league
  password: <%= ENV['LEAGUE_DATABASE_PASSWORD'] %>
